call runsed stage0a.jcl
call runsed stage0b.jcl
call runsed stage0c.jcl
call runsed stage0d.jcl
call runsed stage1a.jcl
call runsed stage1b.jcl
call runsed stage2a.jcl
call runsed stage2b.jcl
call runsed stage2c.jcl
call runsed stage3a.jcl
call runsed stage3b.jcl
call runsed stage3c.jcl
call runsed stage4.jcl
call runsed stage4z.jcl
call runsed gencomp.jcl
call runsed example.jcl
call runsed gccc.prc
call runsed gcccl.prc
call runsed gccclg.prc
